### ISSUE TITLE
Command-line flag for `CLEAR_SYS_MODULES` does not work

### ISSUE THREAD

**Issue by nenb** [rec/impall#19]
:wave: 

**Issue**

`python -m impall --CLEAR_SYS_MODULES` still has `CLEAR_SYS_MODULES = True` (the command-line flag should set it to `False`)

**Why**

The if statement [here](https://github.com/rec/impall/blob/c38722eaa81a1285d4efa2a9967d068121a50186/impall.py#L314-L319) means that when we change the value to `False`, the if-block is skipped, and hence the default value is unchanged.

**Proposed Fix**

Perhaps as simple as setting the default value as `False` and then changing the flag so that it will cause the value to switch to `True`?

**Comment by rec** [comment]
Fixed in impall 1.3, which also removed Python 3.7 compatibility, and a single line dating from Python 2 days.
