### ISSUE TITLE
No `impall.py` since 1.2.0

### ISSUE THREAD

**Issue by MatthijsBurgh** [rec/impall#21]
Since version 1.2.0,  there is no `impall.py`. It disappeared after implementing poetry.

Now the only way to run it in the command line is by using `python -m impall`.

So I suggest you either to update the README or you export it as script again, see https://python-poetry.org/docs/pyproject/#scripts.

**Comment by rec** [comment]
Sorry I didn't get to this yesterday, it was a packed day!

Oops, that was definitely an error, this was the first project I poetried, I don't even have to look at the files to know what I did and how to fix it.

**Comment by MatthijsBurgh** [comment]
Thanks for the quick fix!
