### ISSUE TITLE
Missing tags 1.3 and 1.4

### ISSUE THREAD

**Issue by MatthijsBurgh** [rec/impall#22]
The tags of releases 1.3 and 1.4 are missing. Could you maybe still add them?

**Comment by rec** [comment]
Ouch!

Thank you for keeping me honest here, and for using the package.  I now have a much better set of release scripts that should fix all of that.  I'll also get to this today.

Thanks for using this little program!  I should push it more, I introduced it to someone at my last job and he uses it for everything.

Met vriendelijke groet.

**Comment by rec** [comment]
I added the following tags:

* v1.4.1 (new release)
* v1.4.0
* v1.3.1
* v1.3.0

Thanks again, let me know if there's anything else I can help you with.

(Plug: Also do check out my fine line of other tools! If you like testing, https://github.com/rec/tdir is essential. Safer is good for everything: https://github.com/rec/safer)
